#!/usr/local/bin/python

from socket import AF_INET, SOCK_STREAM
from socket import error as socket_error
from socket import socket
from time import sleep

tries: int = 0
host: str = "postgres"
port: int = 1234

sock: socket = socket(AF_INET, SOCK_STREAM)


while tries <= 1800:
    try:
        sock.connect((host, port))
        sock.close()
        break
    except socket_error as err:
        sleep(0.1)
        tries += 1
